I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/components/inventory_system/inventory.rpy", line 2, in script
    init python:
  File "game/components/inventory_system/inventory.rpy", line 3, in <module>
    from Custom_notification import show_custom_notification  # Import the custom notification function
ModuleNotFoundError: No module named 'Custom_notification'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/components/inventory_system/inventory.rpy", line 2, in script
    init python:
  File "C:\Apps\Renpy\renpy-8.3.3-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Apps\Renpy\renpy-8.3.3-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/components/inventory_system/inventory.rpy", line 3, in <module>
    from Custom_notification import show_custom_notification  # Import the custom notification function
ModuleNotFoundError: No module named 'Custom_notification'

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.3.24111502
Advanced renpy inventory 1.0
Mon Jan 20 17:41:31 2025
